#====================解释部分
# docker-compose -f docker-compose-backend.yml up -d s1 s2 s3 s4
# docker-compose -f docker-compose-backend.yml up -d s0 s2 s3 s4
# docker-compose -f docker-compose-backend.yml restart s0
# 在php代码中的填mysql相关的host，填这里定义的服务名s3_mysql
# 这里写成了/usr/local/nginx/conf/fastcgi_params.conf，没报错，一直空白页，查了好久

version: "3"
services:
  #============================================================================s1a_nginx_上海服务器
  s1a:
    container_name: c1a
    build:
      context: ./services/nginx
      args:
        NGINX_VERSION: 1.15.7-alpine
        CONTAINER_PACKAGE_URL: mirrors.aliyun.com
        TZ: "Asia/Shanghai"
        NGINX_INSTALL_APPS:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www-test:/www-test:rw # 只做测试用
      - ../../888:/888 # 顶级888
      - ./logs/nginx1.15.7:/var/log/nginx/:rw
      - ./services/nginx/ssl:/ssl:rw
      - ./root:/root:rw
      # 6个配置文件拷贝，注意默认安装时nginx的配置目录是 /etc/nginx
      - ./services/nginx/conf/all_websites_shanghai:/etc/nginx/all_websites:ro
      #- ./services/nginx/conf/all_websites_shanghai.conf:/etc/nginx/all_websites.conf
      - ./services/nginx/conf/fastcgi_params:/etc/nginx/fastcgi_params:ro
      - ./services/nginx/conf/fastcgi-php.conf:/etc/nginx/fastcgi-php.conf:ro
      - ./services/nginx/conf/mime.types:/etc/nginx/mime.types:ro
      - ./services/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - "common_volume1:/hunan"
    environment:
      #B_TOP_DIR: /www/server_hongkong
      TZ: "Asia/Shanghai"
      #SERVICE_NAME: s1_nginx
    restart: always
    networks:
      chuse:
        ipv4_address: 172.20.0.8 # 不能为172.20.0.1，它是网关，否则报错 ERROR: for s1a  Cannot start service s1a: Address already in use
  #============================================================================s1b_nginx_香港服务器_支持视频截图
  s1b:
    container_name: c1b
    build:
      context: ./services/nginx
      dockerfile: Dockerfile_video
      args:
        NGINX_VERSION: 1.15.7-alpine
        CONTAINER_PACKAGE_URL: mirrors.aliyun.com
        NGINX_INSTALL_APPS:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www-test:/www-test:rw # 只做测试用
      - ../../888:/888 # 顶级888
      - ./logs/nginx1.15.7:/var/log/nginx/:rw
      - ./services/nginx/ssl:/ssl:rw
      - ./root:/root:rw
      # 6个配置文件拷贝
      - ./services/nginx/conf/all_websites_hongkong:/usr/local/nginx/conf/all_websites:ro
      #- ./services/nginx/conf/all_websites_hongkong.conf:/usr/local/nginx/conf/all_websites.conf:ro
      - ./services/nginx/conf/fastcgi_params:/usr/local/nginx/conf/fastcgi_params:ro
      - ./services/nginx/conf/fastcgi-php.conf:/usr/local/nginx/conf/fastcgi-php.conf:ro
      - ./services/nginx/conf/mime.types:/usr/local/nginx/conf/mime.types:ro
      - ./services/nginx/conf/nginx.conf:/usr/local/nginx/conf/nginx.conf:ro
      - "common_volume1:/hunan"
    environment:
      #B_TOP_DIR: /www/server_hongkong
      TZ: "Asia/Shanghai"
      #SERVICE_NAME: s1_nginx
    restart: always
    networks:
      chuse:
        ipv4_address: 172.20.0.2
        aliases:
          - ad.nginx.zou
          - s1b
          - zou
  #============================================================================s2_php
  s2:
    container_name: c2
    # env_file: ./services/php/.env
    build:
      context: ./services/php
      args:
        #PHP_VERSION: php:7.2.19-fpm-alpine
        PHP_VERSION: php:7.4.6-fpm-alpine3.11
        CONTAINER_PACKAGE_URL: mirrors.aliyun.com
        PHP_EXTENSIONS: pdo_mysql,mysqli,mbstring,gd,curl,opcache,zip,intl
        TZ: "Asia/Shanghai"

    expose:
      - 9501
      - 8000
    ports:
      - "8000:8000"  
    extra_hosts:
      - "www.site1.com:172.17.0.1"
      - "adlightbox.bendi:172.20.0.2"

    volumes:
      - ./www-test:/www-test:rw # 只做测试用
      - ../../888:/888
      - ./logs/php7.2.19:/var/log/php
      - ./data/composer:/tmp/composer
      - ./root:/root:rw
      - ./tmp:/tmp:rw

      # 3个配置文件
      - ./services/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./services/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./services/php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro
      # 证书
      # - ./services/php/cacert.pem:/etc/ssl/cert.pem:ro
      # - ./root/.ssh/id_rsa:/root/.ssh/id_rsa

      #- ./root:/root
      #- ./root/.ssh/id_rsa:/root/.ssh/id_rsa:ro  # 只读权限
      - "common_volume1:/hunan"
      # unable to bind listening socket for address '/var/run/php7-fpm.sock': Operation not permitted (1)
      #/usr/local/etc/php-fpm.d/zz-docker.conf
    environment:
      # B_TOP_DIR: /www/server_hongkong
      TZ: "Asia/Shanghai"
      IN_DOCKER: 'yousheng'
      # SERVICE_NAME: s2
      # NGINX_SERVICE_NAME: s1
    restart: always
    #working_dir: /888/server_hongkong/100_bucaoxin
    working_dir: /888/
    #working_dir: /888/server_shanghai/youshengyouse_net/documents/tailwind
    cap_add:
      - SYS_PTRACE
    networks:
      chuse:
        ipv4_address: 172.20.0.3
  #============================================================================= s3: mysql
  s3:
    container_name: c3
    image: mysql:5.7.28

    ports:
      - "3305:3306"
    volumes:
      - ./services/mysql5/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./data/mysql5:/var/lib/mysql/:rw
    restart: always
    networks:
      chuse:
        ipv4_address: 172.20.0.4
    environment:
      MYSQL_ROOT_PASSWORD: "taobao@1688"
      TZ: "Asia/Shanghai"
  #============================================================================= s4: phpmyadmin
  s4:
    image: phpmyadmin/phpmyadmin:latest
    container_name: c4
    ports:
      - "8081:80"
    volumes:
      - ./services/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:ro
      - ./services/phpmyadmin/php-phpmyadmin.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini:ro
    networks:
      chuse:
        ipv4_address: 172.20.0.5
    environment:
      #- PMA_HOST=mysql
      - PMA_HOST=s3
      - PMA_PORT=3306
      - TZ=Asia/Shanghai
  #============================================================================= s5: redis
  s5:
    image: redis:5.0.3-alpine
    container_name: c5
    ports:
      - "9763:9763" # 将端口6379改为 6399
    volumes:
      - ./services/redis/redis.conf:/etc/redis.conf:ro
      - ./data/redis:/data/:rw
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    environment:
      TZ: "$TZ"
    networks:
      chuse:
        ipv4_address: 172.20.0.6

networks:
  chuse:
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  common_volume1:
